name: Test

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit flake8

      - name: Run Bandit for security analysis
        run: bandit -r server/lti/app

      - name: Run Flake8 for code linting
        run: flake8 server/lti/app